[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "navila-inference"
version = "0.1.0"
requires-python = ">=3.10,<3.11"

dependencies = [
    # Core model stack
    "torch==2.3.0",
    "torchvision==0.18.0",
    "setuptools",
    "transformers==4.37.2",
    "tokenizers>=0.15.2,<0.16",
    "accelerate==0.27.2",
    "peft==0.9.0",
    # Model / tokenizer
    "sentencepiece==0.1.99",
    "shortuuid",
    "safetensors",
    "huggingface-hub",
    # VILA multimodal dependencies
    "einops==0.6.1",
    "einops-exts==0.0.4",
    "timm==0.9.12",
    # Image / video handling
    "numpy==1.26.0",
    "pillow",
    "opencv-python==4.8.0.74",
    "decord==0.6.0",
    "pytorchvideo==0.1.5",
    "matplotlib",
    # Misc dependencies used throughout VILA
    "requests",
    "loguru",
    "hydra-core",
    "tyro",
    # Existing VILA dependency
    "s2wrapper",
    "flash-attn",
    "deepspeed==0.9.5",
    "datasets==2.16.1",
    "custom_utils",
]

[tool.uv.sources]
s2wrapper = { git = "https://github.com/bfshi/scaling_on_scales" }
custom_utils = { workspace = true }
flash-attn = { url = "https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.3cxx11abifalse-cp310-cp310-linux_x86_64.whl" }
# uv pip install --no-deps \
#  "https://github.com/Dao-AILab/flash-attention/releases/download/v2.5.8/flash_attn-2.5.8+cu122torch2.3cxx11abiFALSE-cp310-cp310-linux_x86_64.whl"

# Important because we're going to modify transformers inside .venv.
# We want an isolated physical copy instead of modifying something linked
# against uv's global package cache.
[tool.uv]
link-mode = "copy"


[tool.setuptools.packages.find]
include = ["llava*"]

[tool.uv.workspace]
members = ["custom_utils"]
